// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  angular.module('angularFoundationApp').controller('MainCtrl', function($scope) {
    $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
    return $scope.breadcrumbs = [
      {
        name: 'Home',
        href: '#'
      }, {
        name: 'Features',
        href: '#features',
        unavailable: true
      }, {
        name: 'Whatever',
        href: '#whatever',
        current: true
      }
    ];
  });

}).call(this);
